### ISSUE TITLE
Seedling information

### ISSUE THREAD

**Issue by yezhihe** [CSCvelocityGroup/private-repository#1]
Q: Please provide/add seedling information on the collected data (i.e. Which seedling was used for the each image?). We have reasons to believe that seedling is an important factor that would potentially affect our model and analysis.

**Comment by adm0301** [comment]
In the documents I sent you all titled "TIRF WT actual speed values" and "TIRF mor1-1 actual speed values" you will find the denotations of which file and which kymograph was used for each data point. I will describe the naming system in the second question you asked :]
